### ISSUE TITLE
logic level shifter

### ISSUE THREAD

**Issue by vido89** [szymonh/JTAGscan#5]
Which logic level shifter should I use ?

**Comment by szymonh** [comment]
The main factor to consider here are the voltage levels used by the target and probe.
Generally a range of bidirectional level converters are available on the market from different vendors.
Those are implemented using either dedicated ICs (e.g. TXS0108) or transistors.
Personally I would vote for one or multiple 8-channel bi-directional logic level converters based on a dedicated IC (like the mentioned TXS0108), depending on particular needs.
Of course you could invest more time and effort and design a dedicated PCB to better suit your needs.

**Comment by vido89** [comment]
Will this work https://vi.aliexpress.com/item/32988164907.html ?

**Comment by szymonh** [comment]
This should do the trick for most configurations, please consult documentation from TI to assure it meets your particular requirements.

[https://www.ti.com/product/TXB0108](https://www.ti.com/product/TXB0108)
